version: '3.9'

services:
  textgen_webui:
    image: textgen_webui:latest
    container_name: textgen_webui
    ports:
      - 5000:5000
    environment:
      - TEXTGEN_WEBUI_API_URL=http://0.0.0.0:5000/api
  localai:
    image: localai/localai:latest
    container_name: localai
    ports:
      - 7861:7861
  jupyter_pytorch:
    image: ghcr.io/ai-dock/jupyter-pytorch:2.0.1-py3.9-cuda-11.8.0-devel-22.04
    container_name: jupyter_pytorch
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=password
  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - 8080:80
  django:
    image: django:latest
    container_name: django
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
