FROM ghcr.io/ai-dock/jupyter-pytorch:2.0.1-py3.9-cuda-11.8.0-devel-22.04


WORKDIR /

COPY .env .
COPY app ./cognsh/app
COPY main ./cognsh/main
COPY requirements.txt .
# Expose the environment variables from the .env file
ENV GITHUB_USERNAME=my_github_user
ENV GITHUB_PASSWORD=my_secret_password


RUN pip install -r requirements.txt

CMD ["python", "server.py", "--auto-devices", "--no-stream", "--load-in-8bit", "--listen"]
# docker run --rm -v "$(pwd)/.env:/root/.env" cognsh